### ISSUE TITLE
Weather Underground no longer provides free API keys

### ISSUE THREAD

**Issue by CaninoDev** [learn-co-curriculum/js-weather-api#22]
On 'https://www.wunderground.com/weather/api' June24, 2018 states:

> To improve our services and enhance our relationship with our users, we will no longer provide free weather API keys as part of our program. If you have been directed to download our Weather Underground free API key by a third party provider, please contact your vendor for resolution.

**Comment by maxwellbenton** [comment]
Thanks @CaninoDev, for providing this feedback. This lesson is now using a different API
